
#ifndef VK_PIPELINE_STAGES_TO_STRING
#define VK_PIPELINE_STAGES_TO_STRING

#include <vulkan/vulkan_core.h>
#include <algorithm>
#include <string>

namespace val
{
	inline std::string to_string(const VkPipelineStageFlags flags) {
		std::string res;
		if (flags & VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT) {
			res += "VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT) {
			res += "VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_VERTEX_INPUT_BIT) {
			res += "VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_VERTEX_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT) {
			res += "VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT) {
			res += "VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT) {
			res += "VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT) {
			res += "VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_TRANSFER_BIT) {
			res += "VK_PIPELINE_STAGE_TRANSFER_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT) {
			res += "VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_HOST_BIT) {
			res += "VK_PIPELINE_STAGE_HOST_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT) {
			res += "VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_ALL_COMMANDS_BIT) {
			res += "VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,";
		}
		if (flags & VK_PIPELINE_STAGE_NONE) {
			res += "VK_PIPELINE_STAGE_NONE,";
		}
		if (flags & VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT) {
			res += "VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT,";
		}
		if (flags & VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT) {
			res += "VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT,";
		}
		if (flags & VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR) {
			res += "VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,";
		}
		if (flags & VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR) {
			res += "VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,";
		}
		if (flags & VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR) {
			res += "VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,";
		}
		if (flags & VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV) {
			res += "VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_NV,";
		}
		if (flags & VK_PIPELINE_STAGE_TASK_SHADER_BIT_EXT) {
			res += "VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT,";
		}
		if (flags & VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT) {
			res += "VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT,";
		}
		if (flags & VK_PIPELINE_STAGE_SHADING_RATE_IMAGE_BIT_NV) {
			res += "VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_NV,";
		}

		if (!res.empty()) 
		{
			std::replace(res.begin(), res.end(), ',', '|'); // replace all ',' to '|'
			if (res.back() == '|') {
				res.pop_back();
			}
		}
		return res;
	}
}

#endif // !VK_PIPELINE_STAGES_TO_STRING