
#include <ExternalLibraries/Vulkan/Include/vulkan/vulkan_core.h>

#ifndef VAL_DESC_TYPE_HPP
#define VAL_DESC_TYPE_HPP

enum class DESC_TYPE {
	SAMPLER = VK_DESCRIPTOR_TYPE_SAMPLER,
	COMBINED_SAMPLER = VK_DESCRIPTOR_TYPE_COMBINED_IMAGE_SAMPLER,
	SAMPLED_IMAGE = VK_DESCRIPTOR_TYPE_SAMPLED_IMAGE,
	STORAGE_IMAGE = VK_DESCRIPTOR_TYPE_STORAGE_IMAGE,
	UNIFORM_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_TEXEL_BUFFER,
	STORAGE_TEXEL_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_TEXEL_BUFFER,
	UNIFORM_BUFFER = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER,
	STORAGE_BUFFER = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
	UNIFORM_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_UNIFORM_BUFFER_DYNAMIC,
	STORAGE_BUFFER_DYNAMIC = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER_DYNAMIC,
	INPUT_ATTACHMENT = VK_DESCRIPTOR_TYPE_INPUT_ATTACHMENT,
	INLINE_UNIFORM_BLOCK = VK_DESCRIPTOR_TYPE_INLINE_UNIFORM_BLOCK,
	MUTABLE_EXT = VK_DESCRIPTOR_TYPE_MUTABLE_EXT,
};

#endif // !VAL_DESC_TYPE_HPP