#ifndef VAL_PIPELINE_STAGES_ENUM_HPP
#define VAL_PIPELINE_STAGES_ENUM_HPP

#include <VAL/lib/classEnumBitOps.hpp>
#include <ExternalLibraries/Vulkan/Include/vulkan/vulkan_core.h>

namespace val
{
	enum PIPELINE_STAGE : VkPipelineStageFlags
	{
		TopOfPipe = VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT,
		DrawIndirect = VK_PIPELINE_STAGE_DRAW_INDIRECT_BIT,
		VertexInput = VK_PIPELINE_STAGE_VERTEX_INPUT_BIT,
		VertexShader = VK_PIPELINE_STAGE_VERTEX_SHADER_BIT,
		TessellationControlShader = VK_PIPELINE_STAGE_TESSELLATION_CONTROL_SHADER_BIT,
		TessellationEvaluationShader = VK_PIPELINE_STAGE_TESSELLATION_EVALUATION_SHADER_BIT,
		GeometryShader = VK_PIPELINE_STAGE_GEOMETRY_SHADER_BIT,
		FragmentShader = VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT,
		EarlyFragmentTests = VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT,
		LateFragmentTests = VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT,
		ColorAttachmentOutput = VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT,
		ComputeShader = VK_PIPELINE_STAGE_COMPUTE_SHADER_BIT,
		Transfer = VK_PIPELINE_STAGE_TRANSFER_BIT,
		BottomOfPipe = VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT,
		Host = VK_PIPELINE_STAGE_HOST_BIT,
		AllGraphics = VK_PIPELINE_STAGE_ALL_GRAPHICS_BIT,
		AllCommands = VK_PIPELINE_STAGE_ALL_COMMANDS_BIT,
		None = VK_PIPELINE_STAGE_NONE,
		TransformFeedback = VK_PIPELINE_STAGE_TRANSFORM_FEEDBACK_BIT_EXT,
		ConditionalRendering = VK_PIPELINE_STAGE_CONDITIONAL_RENDERING_BIT_EXT,
		AccelerationStructureBuild = VK_PIPELINE_STAGE_ACCELERATION_STRUCTURE_BUILD_BIT_KHR,
		RayTracingShader = VK_PIPELINE_STAGE_RAY_TRACING_SHADER_BIT_KHR,
		FragmentDensityProcess = VK_PIPELINE_STAGE_FRAGMENT_DENSITY_PROCESS_BIT_EXT,
		FragmentShadingRateAttachment = VK_PIPELINE_STAGE_FRAGMENT_SHADING_RATE_ATTACHMENT_BIT_KHR,
		TaskShader = VK_PIPELINE_STAGE_TASK_SHADER_BIT_EXT,
		MeshShader = VK_PIPELINE_STAGE_MESH_SHADER_BIT_EXT,
		CommandPreprocess = VK_PIPELINE_STAGE_COMMAND_PREPROCESS_BIT_EXT,
		ShadingRateImage = FragmentShadingRateAttachment
	};

#ifndef VAL_PIPELINE_SHADER_STAGES_BITWISE_OPS
#define VAL_PIPELINE_SHADER_STAGES_BITWISE_OPS
	DEF_ENUM_BITWISE_OPERATORS(PIPELINE_STAGE)
#endif // !VAL_PIPELINE_SHADER_STAGES_BITWISE_OPS

}

#endif // !VAL_PIPELINE_STAGES_ENUM_HPP