#version 460
#extension GL_EXT_ray_tracing : require

layout(set = 0, binding = 0) uniform accelerationStructureEXT topLevelAS;
layout(set = 0, binding = 1, rgba32f) uniform image2D imgOut;

layout(location = 0) rayPayloadEXT vec3 payload;

layout(set = 0, binding = 2) uniform Uniforms {
    mat4 viewInverse;
    mat4 projInverse;
    vec2 resolution;
} uni;


/////////////////////////////////////////////////////////////////////////
// This code is from Thorsten Thormählen's Vulkan raytracing examples.
// https://www.gsn-lib.org/docs/nodes/raytracing.php



// Returns a camera ray for a camera at the origin that is looking in negative z-direction.
// "fieldOfViewY" must be given in degrees.
// "point" must be in range [0.0, 1.0] to cover the complete image plane.
//
vec3 getCameraRay(float fieldOfViewY, float aspectRatio, vec2 point) {
  // compute focal length from given field-of-view
  float focalLength = 1.0 / tan(0.5 * fieldOfViewY * 3.14159265359 / 180.0);
  // compute position in the camera's image plane in range [-1.0, 1.0]
  vec2 pos = 2.0 * (point - 0.5);
  return normalize(vec3(pos.x * aspectRatio, pos.y, -focalLength));
}


void main() { // **** RAY GENERATION SHADER ****

    // Get screen-space normalized coordinates in [0,1]
    vec2 texCoord = (vec2(gl_LaunchIDEXT.xy) + 0.5) / vec2(gl_LaunchSizeEXT.xy);

    // scale and center to [-1,1] range
    vec2 centeredUV = texCoord * 2.0 - 1.0;

    // Define viewport size (in world units)
    float orthoWidth = 1.0;
    float orthoHeight = orthoWidth * (float(gl_LaunchSizeEXT.y) / float(gl_LaunchSizeEXT.x));

    // Compute origin in world space (on XY plane)
    vec3 rayOrigin = vec3(centeredUV.x * orthoWidth * 0.5,
                          centeredUV.y * orthoHeight * 0.5,
                          1.5); // z = 10 units above

    // Orthographic rays all point downward in -Z
    vec3 rayDirection = vec3(0.0, 0.0, -1.0);

    uint rayFlags = gl_RayFlagsNoneEXT;
    float rayMin = 0.001;
    float rayMax = 1000.0;
    uint cullMask = 0xFFu;

    payload=vec3(0,0,0);

    traceRayEXT(topLevelAS,
                rayFlags,
                cullMask,
                0u, 0u, 0u,
                rayOrigin, rayMin,
                rayDirection, rayMax,
                0);

    imageStore(imgOut, ivec2(gl_LaunchIDEXT.xy), vec4(payload, 1.0));
}